steps:

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args: 
      [
        'build', 
        '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/my-app:$COMMIT_SHA',
        '-t', 'docker.io/${_DOCKER_USER}/my-app:$COMMIT_SHA',
        '-f', 'bitcoin-app/Dockerfile', 
        'bitcoin-app'                         
      ]


  - name: 'debian:bullseye-slim'
    id: 'Scan Image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | tee -a /etc/apt/sources.list.d/trivy.list
        apt-get update && apt-get install -y trivy
        trivy image --exit-code 0 --severity HIGH,CRITICAL us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/my-app:$COMMIT_SHA

        
 
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push to GCP'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/my-app:$COMMIT_SHA']


  - name: 'gcr.io/cloud-builders/docker'
    id: 'Docker Hub Login'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$DOCKER_PASSWORD" | docker login --username $$DOCKER_USERNAME --password-stdin
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']


  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push to Docker Hub'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push docker.io/${_DOCKER_USER}/my-app:$COMMIT_SHA

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Create Cloud Deploy Release'
    entrypoint: gcloud
    args:
      [
        'deploy', 'releases', 'create', 'rel-$SHORT_SHA',
        '--delivery-pipeline', 'my-app-pipeline',
        '--region', 'us-central1',
        '--annotations', 'commitId=$COMMIT_SHA',
        '--images', 'my-app-image=us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/my-app:$COMMIT_SHA'
      ]

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/DOCKER_USERNAME_SECRET/versions/latest
    env: 'DOCKER_USERNAME'
  - versionName: projects/$PROJECT_ID/secrets/DOCKER_PASSWORD_SECRET/versions/latest
    env: 'DOCKER_PASSWORD'

substitutions:
  _DOCKER_USER: 'rukevweubio' 

options:
  logging: CLOUD_LOGGING_ONLY